### ISSUE TITLE
Improve detection of default sizing_mode

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1059]
#### My Pain

With Panel 0.8.0 we can set a global, default sizing_mode. For example stretch_width to make things full width, responsive by default. And thats really great. 

But sometimes you wan't a specific pane, layout or widget to have a fixed width and then the friction starts. Because then you have to both specify a width and sizing_mode when you instantiate the object.

In my experience I forget the sizing_mode and thus waste some time on testing and debugging. Or if I remember my code gets less compact.

An example is 

```python
import panel as pn

pn.config.sizing_mode = "stretch_width"

is_not_fixed_width = pn.Row("# Is not fixed width", background="salmon", width=300)
is_fixed_width = pn.Row("# Is fixed width", background="orange", width=300, sizing_mode="fixed")

pn.Column(is_not_fixed_width, is_fixed_width, background="lightgray").servable()
```

![image](https://user-images.githubusercontent.com/42288570/73588568-10418280-44cb-11ea-911b-2932021d2b19.png)

Its simply not logical (to me) that I have to set two attributes to get fixed width.

#### Solution

Implement functionality that handles both 1) constructing an object width a fixed width 2) changing the width dynamically.

#### Additional Context

I can live with things as they are for now. But one day if somebody has the time it would be really a nice thing to improve.

At awesome-panel.org I have developed a Card layout that inherits the Column layout. I've tried to handle the above in the constructor for now

In this example the default is always `sizing_mode = "stretch_width"`.

```python
class Card(pn.Column):
    """A Card inspired by the Bootstrap Card"""

    def __init__(
        self,
        header: str,
        body: Union[pn.viewable.Viewable, List[pn.viewable.Viewable],],
        collapsable: bool = False,
        **kwargs,
    ):
       if "sizing_mode" not in kwargs:
            if "width" not in kwargs and "height" not in kwargs:
                kwargs["sizing_mode"] = "stretch_width"
            elif "width" in kwargs and "height" in kwargs:
                kwargs["sizing_mode"] = "fixed"
            elif "width" in kwargs:
                kwargs["sizing_mode"] = "stretch_height"
            elif "height" in kwargs:
                kwargs["sizing_mode"] = "stretch_width"
.....
```

**Comment by xavArtley** [comment]
@philippjfr will correct me but I think when you set `strecth` and a value for `width` or `height` it acts like a mnimum value.

**Comment by mattpap** [comment]
> Its simply not logical (to me) that I have to set two attributes to get fixed width.

From bokeh's perspective (and I presume that panel simply inherits this behavior), setting `width` (or `height`) doesn't mean it's a fixed size, but its meaning depends on the sizing mode. For `fixed` sizing mode this is indeed a fixed size, otherwise it's a starting point for layout size optimization (within min/max size bounds). If that's desired, panel as a higher-level API than bokeh, can make things simpler for the user and not expose this low-level logic.

**Comment by mattpap** [comment]
Additionally setting `fixed` sizing mode without setting `width` or `height` also makes sense, because then those sizes will be either inferred or computed depending on the other factors (e.g. intrinsic size will be used in the case of HTML forms). Setting `fixed` sizing mode means that the dimensions won't be altered during fitting phase of the layout (e.g. layout will overflow if it can't be fitted), but the exact values don't have to originate from user provided constants.
