### ISSUE TITLE
PointCloud

### ISSUE THREAD

**Issue by tchaton** [holoviz/panel#1105]
Dear people of Panel,

I was wondering if there would be a way to handle pointcloud using panel (using potree extension for example) or vtk.

Best,
Thomas Chaton.

**Comment by jbednar** [comment]
Depends what you need, but VTK and Plotly should both be able to handle points embedded in 3D space.

**Comment by tchaton** [comment]
Dear @jbednar,

Thanks for the quick answer, I will have a look then.

Best,
Thomas Chaton.

**Comment by jbednar** [comment]
If you have millions of points, you'll probably want to aggregate them into a volume and visualize that instead of the underlying points.  vaex works well for that 3D aggregation, and then you can use ipyvolume (only available using Bokeh 2.0, which is arriving shortly) or VTK to visualize the volume.  If the points happen to represent a surface, you can use Datashader's 2D aggregation; see https://earthml.holoviz.org/topics/Seattle_Lidar.html .
