### ISSUE TITLE
Please add Folium pane

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1192]
#### My Pain

I would like Panel to be great and support the most common python visualization libraries and associated js libraries.

One such Python Package is Folium. You can use a Folium map in Panel using `pn.pane.HTML` but if you try to make the map interactive it redraws the whole `_repr_html_` from scratch every time making the screen flickr.

#### Solution

Add panel Folium pane based on a Folium Bokeh model.

#### Additional Context

You can experience the flickr via this contribution https://github.com/holoviz/panel/pull/1189

![panel_folium_example](https://user-images.githubusercontent.com/42288570/77608167-ba161c00-6f1c-11ea-818a-662efcda5839.gif)

**Comment by jbednar** [comment]
At the 2018 SciPy conference, the main author of Folium (https://github.com/ocefpaf) suggested that it was not something he was recommending that people use anymore; has that changed?

**Comment by MarcSkovMadsen** [comment]
Hi @jbednar . I did not attend and have not heard about that.

What I can see is that it is 7 times more starred than Panel and there is activity

![image](https://user-images.githubusercontent.com/42288570/77618545-d1620300-6f36-11ea-9166-746b07d31a0f.png)

**Comment by MarcSkovMadsen** [comment]
But @jbednar  I guess the feature request should be extended to a Folium + Leaflet.js pane?

**Comment by philippjfr** [comment]
Doesn't seem to be stopping people:

![Screen Shot 2020-03-26 at 5 10 32 AM](https://user-images.githubusercontent.com/1550771/77609386-25152200-6f20-11ea-9aa8-a46ccc704fb3.png)

**Comment by jbednar** [comment]
Ok, I've talked to Filipe, who clarified that Folium has a strong future as long as people realize that it is expected to remain a one-way street, constructing JS artifacts from Python _without_ providing a pathway to return data back to Python/Jupyter/JupyterLab.  If users need two-way communication of that sort, Filipe suggests they look to other tools like Bokeh or ipyleaflet. 

With that in mind, providing a Folium Pane sounds very reasonable, so that people can make use of all the Folium examples that are out there! Filipe also clarified that Frank Conengmo (https://github.com/Conengmo) is the new Folium maintainer, and so we should follow up with him if we want to chat about the Folium roadmap.

**Comment by philippjfr** [comment]
A basic Folium pane was merged, and I don't think the flicker is actually avoidable because Folium does not have JS bindings which would allow us to update the map/plot incrementally.
