### ISSUE TITLE
Is there a way to propogate options recursively through all holoviews objects and layouts?

### ISSUE THREAD

**Issue by LinuxIsCool** [holoviz/panel#1228]
I have deeply nested panel rows and columns with nested holoviews ndlayouts, is there a way to set (plot1 + plot2).opts(opts.Scatter(axiswise=True)), all the way down recursively on all layouts?

Thank you.

**Comment by philippjfr** [comment]
Thanks for the issue but I'm slightly confused by your question. That is exactly what the syntax you described already does. I'm guessing you have other element types that are being normalized together which is why you're getting the effect you're seeing. Maybe try just setting `.opts(shared_axes=False)`. Otherwise there are already issues about being able to set options on any element, which would be great to have.

**Comment by philippjfr** [comment]
Oh also this is definitely a HoloViews issue and for usage questions it's best to post on the Discourse.
