### ISSUE TITLE
FileDownload button does not stretch

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1289]
#### System Info

Panel 0.9.4

#### My Pain

I'm trying to create a Panel app with a Column of user selections and actions. In that column I have some Buttons and a FileDownload widget. I would like those buttons to align nicely below each other.

I cannot get that to work as the FileDownload button does not stretch.

![image](https://user-images.githubusercontent.com/42288570/79766128-d5abf100-8327-11ea-9348-56593c36f54f.png)

#### Code

```python
import panel as pn

download_widget = pn.widgets.FileDownload(name="Download stretched", sizing_mode="stretch_width", background="lightgray")
download_widget2 = pn.widgets.FileDownload(name="Download fixed", width=500, background="salmon")
button = pn.widgets.Button(name="Button", sizing_mode="stretch_width")

app = pn.Column(
    download_widget,
    download_widget2,
    button,
    width=600,
    background="gray",
  )

app.servable()
```

**Comment by maximlt** [comment]
I tried to track this bug down and here is what I found.

The ``FileDownload`` widget is actually based on the bokeh ``InputWidget`` model (it inherits from ``InputWidgetView``). A bokeh ``InputWidget`` is a ``div`` HTML that contains:
1. a label
2. an input element

The style of the ``div`` is ``bk-input-group``.

The second element is usually an HTML ``input`` but it could be something else such as a ``select`` to create the bokeh ``Select`` widget. Whatever this element is in bokeh its style appears to be ``bk-input`` that is defined [here]( https://github.com/bokeh/bokeh/blob/e8b22ef161bae542ca06fe77cb12129ca7e3d870/bokehjs/src/less/widgets/inputs.less#L4).

In panel the second element is an ``anchor`` that with a ``download`` attribute allows to create a downloadable link. How come does it look like a button then? Well because the style of this anchor element is inherited from the bokeh ``Button`` widget, exactly from ``bk-btn`` and ``bk-btn-default`` (or ``bk-btn-danger``, etc.) defined [here](https://github.com/bokeh/bokeh/blob/e8b22ef161bae542ca06fe77cb12129ca7e3d870/bokehjs/src/less/buttons.less#L4) in bokeh.

As showed by @MarcSkovMadsen the whole ``div`` actually stretches correctly when ``sizing_mode = "stretch_width``. So somehow that button style doesn't seem to fit well here and causes the described bug. I had a look at these style files in bokeh and could just notice that they seem to stretch the elements in different ways, I can't say more unfortunately.

Someone with better CSS/HTML/Javascripts will have to figure out the way forward here! ;)

**Comment by itsgifnotjiff** [comment]
Using Panel 1.3.8 I get the following weird behaviour which I do not get using 1.2.3 (I tried setting `sizing_mode` as well).
Basically `DiscretePlayer` and `FileDownload` in `1.3.8` seem to have some broken CSS.
![image](https://github.com/holoviz/panel/assets/50274281/6104b847-ff6c-4534-848a-ae126805a0d3)

**Comment by philippjfr** [comment]
@itsgifnotjiff Have you tried 1.4.0?
