### ISSUE TITLE
APIs Reactive Functions only work partially

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1379]
At https://panel.holoviz.org/user_guide/APIs.html I am trying out the Reactive example. The plot updates to changes in the `x` and `y` value. But not the `color` value.

![image](https://user-images.githubusercontent.com/42288570/83391593-00439c00-a3f4-11ea-8a67-62956db8bd15.png)

**Comment by xavArtley** [comment]
For me the example works

**Comment by philippjfr** [comment]
I think @MarcSkovMadsen means on the website itself, which indeed does not work. I think we should probably work on disabling widgets which do not or cannot work on the website.

**Comment by jbednar** [comment]
Would it be possible for us to make a watermark that we overlay on top of panes or widgets that aren't supported in a static export, with tilted or otherwise distinguishable text saying something like "Requires live Python server"?

**Comment by EricVirag** [comment]
@jbednar  I would like to know if dateRangeSlider widget requires a live Python server?

**Comment by jbednar** [comment]
No particular widget requires a live server; it's the connection from the widget to something that would require a server. For instance, you should be able to use .jslink to connect the widget to a property of a Bokeh plot, so that the DateRangeSlider widget controls the x axis range. Such a connection would be done entire at the JavaScript level, implemented by your local client browser, and would thus work on a website or in a static exported file.  But if you connect that same widget up to a callback written in Python that e.g. does a database query for that date range, then the widget will have no effect without Python running. That's how Panel works in general -- the basic machinery is all set up to work either with Python or with JavaScript, and if you stick with JavaScript connections and JavaScript callbacks, then you won't need Python.

**Comment by philippjfr** [comment]
We now have interactivity warnings on all pages.
