### ISSUE TITLE
Do not use Param before __init__

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1418]
#### My Pain

Trying to use Panel for a larger app. But it did not work and it took me an hour to track down the problem. 

I don't know if this is a bug or if it is just me doing something which is not supported.

#### Does not work

The problem here is that the css text box is empty

![image](https://user-images.githubusercontent.com/42288570/84856119-11ccab00-b066-11ea-935b-162d8a874eb9.png)

```python
import param
import panel as pn

class AppStyler(param.Parameterized):
    body_color = param.String("#000000")

    css = param.String()

    view = param.Parameter()

    def __init__(self, **params):
        params["view"] = pn.Column(pn.Param(self, parameters=["body_color"]), pn.Param(self, parameters=["css"]))

        super().__init__(**params)



        self._update_css()

    @param.depends("body_color", watch=True)
    def _update_css(self):
        print("updating")
        self.css = self.body_color

    @param.depends("css", watch=True)
    def _update_css_pane(self):
        pass

AppStyler().view.servable()
```

#### Works

By moving the view line below the `super().__init__` it works

![image](https://user-images.githubusercontent.com/42288570/84856200-4fc9cf00-b066-11ea-9480-4464632d6d5a.png)

```python
import param
import panel as pn

class AppStyler(param.Parameterized):
    body_color = param.String("#000000")

    css = param.String()

    view = param.Parameter()

    def __init__(self, **params):
        super().__init__(**params)

        self.view = pn.Column(pn.Param(self, parameters=["body_color"]), pn.Param(self, parameters=["css"]))

        self._update_css()

    @param.depends("body_color", watch=True)
    def _update_css(self):
        print("updating")
        self.css = self.body_color

    @param.depends("css", watch=True)
    def _update_css_pane(self):
        pass

AppStyler().view.servable()
```

**Comment by jbednar** [comment]
Until the `super().__init__(**params)` call, nothing provided by Parameterized is available, so this behavior is expected.  As far as I know there is nothing that could be done about it; without that call the superclass's `__init__` method is not called, and thus nothing to do with Parameters is initialized.  See https://github.com/holoviz/param/blob/master/param/parameterized.py#L2380 for all the things  that happen that you'll miss out if you try to do anything before that call. Usually we try to avoid having `__init__` methods in Parameterized subclasses at all, so that they are shorter and easier to reason about, but sometimes they are needed.
