### ISSUE TITLE
Shared Axes on Holoviews Plots

### ISSUE THREAD

**Issue by balast** [holoviz/panel#1572]
#### ALL software version info
- python==3.8.5
- pandas==1.1.2
- panel==0.9.7
- holoviews==1.13.3
- jupyterlab==2.2.7
#### Description of expected behavior and the observed behavior
I am new to panel, and perhaps this is expected behavior, but it's not what I would have expected, and I can't find information about it in the docs. I created 2 holoviews plots of the same type in a pn.Column. The axes on the plots are linked by default, but I wouldn't expect them to be linked by default.

#### Complete, minimal, self-contained example code that reproduces the issue

```python3
import panel as pn
import holoviews as hv
import pandas as pd

pn.extension()
hv.extension('bokeh')

sample_data = pd.DataFrame([1,2,3,4,5], columns=['a'], index=range(0,5))
sample_data2 = pd.DataFrame([5,4,3,2,1], columns=['b'], index=range(5,10))
pn.Column(
    hv.Bars(sample_data, 'index', 'a'), # changing this line to hv.Bars(sample_data, 'index', 'a').opts(shared_axes=False) fixes the problem
    hv.Bars(sample_data2, 'index', 'b'),
)
```
#### Screenshots or screencasts of the bug in action
![image](https://user-images.githubusercontent.com/23342526/92677145-ba4a7e00-f2e8-11ea-9d77-2472780856c3.png)

**Comment by xavArtley** [comment]
From the doc it's the expected behavior:

![Capture d’écran de 2020-09-10 07-00-01](https://user-images.githubusercontent.com/18531147/92683495-51d4be80-f333-11ea-9ba7-2fdc3fd93f48.png)


```python
import panel as pn
import holoviews as hv
import pandas as pd

pn.extension()
hv.extension('bokeh')

sample_data = pd.DataFrame([1,2,3,4,5], columns=['a'], index=range(0,5))
sample_data2 = pd.DataFrame([5,4,3,2,1], columns=['b'], index=range(5,10))
hpan1 = pn.pane.HoloViews(hv.Bars(sample_data, 'index', 'a'), linked_axes=False)
hpan2 = pn.pane.HoloViews(hv.Bars(sample_data2, 'index', 'b'), linked_axes=False)

pn.Column(
    hpan1,
    hpan2
)
```

![Capture d’écran de 2020-09-10 07-01-53](https://user-images.githubusercontent.com/18531147/92683605-9b250e00-f333-11ea-81f2-8ef307af58d2.png)

**Comment by jbednar** [comment]
Here the wrapping as a pane was needed only so that pane options can be specified. Panel layouts already call `pn.panel()` on each of their arguments, which automatically wraps a HoloViews object with a HoloViews pane. In fact, you don't need to specify the pane type explicitly if you don't want to; calling `pn.panel()` yourself as `pn.panel(hv.Bars(sample_data, 'index', 'a'), linked_axes=False)`) will let you pass pane arguments without having to remember what type of pane you're creating.

You should also be able to control the linking at the HoloViews level, avoiding having to specify `pn.panel` at all, but I forget how to spell that (possibly `.opts(shared_axes=False`).
