### ISSUE TITLE
Reserved keywords when working with interact

### ISSUE THREAD

**Issue by Hoxbro** [holoviz/panel#1790]
#### Is your feature request related to a problem? Please describe.
When using `pn.interact` there is some keywords which is used for the widget layout like `width`. When using these keywords in a function it gives a ValueError related to the widget layout and not the function input.  See example here:
```python
import panel as pn
pn.extension()


def example_function(width=300):
    return width

pn.interact(example_function, width=300)  # Does not give error
pn.interact(example_function, width=(0, 10000, 10, 300))  # Gives ValueError: Parameter 'width' must be an integer.
```

#### Describe the solution you'd like
It would be nice if it gave a more clear error / warning like `width is reserved for pn.interact use another variable name`.

**Comment by jlstevens** [comment]
I've given this an enhancement label as this is not expected to ever work but as you point out, it would very helpful to issue a better error message.

**Comment by jbednar** [comment]
I wonder if such arguments could be made to work if we checked the function signature _before_ processing parameter values. I do think an explicit argument name in the provided function should override any parameter whose value we are accepting in `interact`, since the user presumably knows their own function much better than all the options supported by `interact` that they may not be using anyway. Seems like we could pop off any of the keyword arguments of the function before calling the superclass to handle the params, then use those later?

**Comment by jlstevens** [comment]
That was a different approach from what I had in mind which was to inspect the supplied function signature and compare it to interacts own parameters and then generate a better error message.

I can't tell whether your suggestion would be confusing (as then you couldn't set those clashing parameters for interact) or helpful because more possible keyword arguments in user defined functions would work. On balance, I think admitting the clash with an error would be best as users may well have a clash *and* want to use the functionality of the interact parameters of the same name.

**Comment by jbednar** [comment]
Users could still do that, if they renamed their function arguments; in my proposal it would just be much rarer that users would need to rename their arguments. In any case, I think either approach would be a big improvement, and am happy with either one.

**Comment by jlstevens** [comment]
Your suggestion is probably better than an error as long as a warning acknowledging the clash is issued.

**Comment by philippjfr** [comment]
Closing all `interact` related issues. While not officially deprecated we no longer advertise it and will not provide support for it.
