### ISSUE TITLE
Widget docs title capitalisation

### ISSUE THREAD

**Issue by cdeil** [holoviz/panel#1803]
If you go to widget docs pages like this:
* https://panel.holoviz.org/reference/widgets/DatetimeInput.html
* https://panel.holoviz.org/reference/widgets/DatetimeRangeInput.html

Currently the page title doesn't show the class name with proper capitalisation, it's displayed as `Datetimeinput` and `Datetimerangeinput`. This is confusing, I was getting an error and it took me a minute to realise it's the typo in `Datetimeinput` vs `DatetimeInput`.

Maybe this is something that's easy to fix in the docs build in one place for all widgets, given that the notebook filenames and content is correct already?

![Screenshot 2020-11-24 at 22 27 13](https://user-images.githubusercontent.com/852409/100153292-35f9a700-2ea4-11eb-8f15-d7233f7dad4b.png)

**Comment by jbednar** [comment]
Yes; I think it's an issue in [nbsite](https://github.com/pyviz-dev/nbsite/), and it's annoyed me as well. I'd guess it's a simple fix, changing something that does `str.capitalize()` (which, utterly non-intuitively to me, _lowers_ everything first), so that instead it does `str[:1].upper() + str[1:]`

**Comment by philippjfr** [comment]
Fixed on master:

<img width="1030" alt="Screen Shot 2022-08-14 at 11 46 57" src="https://user-images.githubusercontent.com/1550771/184531477-c497c6e2-decf-4b25-91fb-def5cd26d002.png">
