### ISSUE TITLE
Make it really easy to run tasks and responses asynchronously

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1864]
Right now there are not a lot of examples of running tasks in the background and/ or responding asynchronously with Panel. But Panel is running on Tornado. So it should be possible.

The use case I see the most is 

- ETL: Extract data from some where. Transform it (dataframe) and load it to somewhere.
- Transform: Transform data that has already been loaded.
- Model: run models
- Plots: create plots.

Right now these things "block" our apps when running. My feeling is that it would be easy to make some kind of decorator that turns a function into an asynchronous function.

That would help make our apps much more responsive and with a modern feel.

**Comment by philippjfr** [comment]
>My feeling is that it would be easy to make some kind of decorator that turns a function into an asynchronous function.

No need for a decorator, simply use a regular `async` function as a `.param.watch` callback. Definitely need a bunch of examples here though. Note also that none of the use cases you list would benefit at all from being asynchronous, async code is only useful if you're waiting on some blocking I/O, e.g. fetching files/data from a server/database/filesystem. If you want to avoid blocking on computations you need to run the computation on another thread.

**Comment by nghenzi** [comment]
Sorry to get into the conversation, but a few thread examples or pattern recommendations would be nice. In my application I have a global thread to update some global dictionaries for all users. Also, I create a local thread for each user within the function that the app serves for that user (clarification: to update the bokeh models of the different threads, I use the add next tick callback).

I have 2 issues with this pattern, one is related to the fact that local threads keep working until the session is closed (60 seconds after the tab in the client is closed) because I think there is nothing like `pn.on_unload` ??. The second problem is that sometimes an error appears related to the bokeh model that is already in use. This is once or twice a week, so I don't know if this is actually related to threads or another problem in the application. The question is can I run 20 threads at the same time?

**Comment by philippjfr** [comment]
Async callbacks are now well supported throughout and the how-to guide has examples. If there's examples missing then we should file specific issues about those but I'll consider this task as done.
