### ISSUE TITLE
Templates user guide output broken

### ISSUE THREAD

**Issue by philippjfr** [holoviz/panel#2329]
The template shown in https://panel.holoviz.org/user_guide/Templates.html is currently not rendering because it does not wait for Bokeh to be loaded to attempt rendering.

**Comment by emcd** [comment]
The link referenced in the original comment of this issue seems to be broken. Would like to know more details on the problem reported in this issue in case it matches what I am seeing with roots not rendering in a custom template due to Bokeh not finding some UUID-like HTML tag. E.g.:
```
bokeh.min.js?v=212dd2b37e44c65bf8be6c056df157eb58e0e994fee403257354478fd32acc76023ab2c9d53094ed0751dab7f3983ef01ca85785ea82c9c873a9dc8b231245bd:230 Uncaught (in promise) Error: Error rendering Bokeh model: could not find #39cc1fb1-5f55-4e0d-840b-07d0330b1d10 HTML tag
```

Happens in both Chrome and Firefox, so I don't think it is exactly the same problem as reported in [this Discourse thread](https://discourse.holoviz.org/t/goldentemplate-issues/3222/12).

**Comment by philippjfr** [comment]
That user guide doesn't exist anymore.
