### ISSUE TITLE
Can't sort widget DataFrame values with `hierarchical=True`

### ISSUE THREAD

**Issue by epassaro** [holoviz/panel#2388]
#### ALL software version info
bokeh 2.3.2
panel 0.11.3

#### Description of expected behavior and the observed behavior

Created a DataFrame widget. Can't sort values by clicking header when `hierarchical=True` is used.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import bokeh
import panel as pn

pn.extension()
bokeh.sampledata.download()

from bokeh.sampledata.population import data as population_data 

pop_df = population_data[population_data.Year == 2020].set_index(['Location', 'AgeGrp', 'Sex'])[['Value']]
pn.widgets.DataFrame(value=pop_df, hierarchical=True, aggregators={'Sex': 'sum', 'AgeGrp': 'sum'}, height=400)

```

**Comment by MarcSkovMadsen** [comment]
I can confirm that the provide example can be used to reproduce the bug on the current master branch (pre panel 0.12).

https://user-images.githubusercontent.com/42288570/122653766-38289900-d147-11eb-87ae-63d98617227d.mp4

I don't know if this is a bug, expected behavior or if this should be a Feature Request though @philippjfr ?

**Comment by philippjfr** [comment]
So this would almost certainly require changes in Bokeh since that is where the DataTable (or rather the `DataCube` used for hierarchical rendering) is implemented. So I'd suggest opening an issue there. Sorry for the hassle.
