### ISSUE TITLE
Would it be possible to create a @pn.js_depends?

### ISSUE THREAD

**Issue by andhuang-CLGX** [holoviz/panel#2552]
Something like:
```
import param
import panel as pn
import holoviews as hv
pn.extension()

class Test(param.Parameterized):
    alpha_value = param.Number(default=1, bounds=(0, 1), step=0.01)

    def __init__(self, **params):
        super(Test, self).__init__(**params)

    @pn.js_depends("alpha_value", "glyph.alpha")
    def view(self):
        return hv.Curve(([0, 1, 2], [3, 4, 5]))
```

**Comment by jbednar** [comment]
What it looks like you are proposing isn't really js_depends but more specifically bokeh_js_depends, because the proposal is to jslink from the given parameter to the given Bokeh property, right? I don't think that fits with the semantics of @depends, which is a declaration that the given Python method should be rerun when the parameter changes. js_depends would then re-run a JS method, and there's no JS method here. Instead this seems like a case for adding a jslink call inside `view`, so that the result of calling `view` is an object that is jslinked to the parameter (widget).

**Comment by andhuang-CLGX** [comment]
Maybe not just bokeh_js_depends
```
pn.js_depends("alpha_value", "object")
def view(self):
        return pn.pane.Markdown()
```

**Comment by jbednar** [comment]
Sure. Let's close this one and focus on the other one, as a simpler way to do a jslink seems very feasible, while "depending" in a Python codebase in a situation where you can't run Python code is messy.
