### ISSUE TITLE
IPywidgets reference guide does not mention you should add "ipywidgets" to pn.extension

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2594]
I'm creating a larger app where I optionally want to display Ipywidgets/ IPyleaflet if a button is clicked. I can see that in order for ipyleaflet to get loaded on button click I need to "ipywidgets" when I run `pn.extension`. This is not mentioned in the reference guide https://panel.holoviz.org/reference/panes/IPyWidget.html#panes-gallery-ipywidget.

![image](https://user-images.githubusercontent.com/42288570/127739922-d8d56e11-1504-42fa-a981-98e4385d60db.png)

## Solution

Replace `pn.extension` with `pn.extension("ipywidgets")` in the reference guide.

## Additional Context

If I instantiate ipyleaflet as a part of serving the application ipyleaflet loads without problems.

**Comment by philippjfr** [comment]
It's a slightly hairy issue, the problem is that if you load `pn.extension('ipywidgets')` in JupyterLab this will break the entire JupyterLab UI, which is why for the notebook we use a completely separate ipywidgets implementation. That said the reference guide is exactly the right place to explain those caveats.
