### ISSUE TITLE
Jupyterlab "Render with panel" preview page not found 404

### ISSUE THREAD

**Issue by josselex** [holoviz/panel#2630]
#### ALL software version info

```
jupyterlab=3.0.16 
or
jupyterlab=3.1.4 


jupyter-bokeh=3.0.2
pyviz_comms=2.1.0
panel=0.12.1
bokeh=2.3.3
```

#### Complete, minimal, self-contained example code that reproduces the issue

1. Starting the panel-examples server with `jupyter lab`.
2. open for examaple `user_guide/Deploy_and_Export.ipynb`
3. press "Render with panel" menu button
4. A new tab shows up with a 404 error

#### Stack traceback and/or browser JavaScript console output

The jupyter service logs the following:

```
[W 2021-08-12 08:17:00.550 ServerApp] 404 GET /panel-preview/render/user_guide/Deploy_and_Export.ipynb (::1) 1.00ms referer=None
```

**Comment by philippjfr** [comment]
Have you enabled the server extension with:

```bash
jupyter serverextension enable panel.io.jupyter_server_extension
```

**Comment by philippjfr** [comment]
Going to assume we simply need to document this better for now.

**Comment by philippjfr** [comment]
>Yes. Where is this supposed to be documented?

Probably forgot to add it since initially I assumed it would automatically activate on install, but that's clearly not the case.

>Also somehow this should be tied to the button showing up. If it shows up, it is supposed to work, I guess.

That would indeed be nice, unfortunately the JupyterLab extension, which is now installed automatically, is completely separate from the jupyter server extension which has to be enabled explicitly.
