### ISSUE TITLE
Panel Jupyterpreview does not start from folder of the notebook

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2693]
Normally when a users run a notebook it runs from the folder where the notebook is located. The same happens when users start the Voila Jupyter Preview. The same happens when using ContainDS in your Jupyter Hub.

But the Panel Jupyter Preview does not start from the folder of the file. 

The consequence is that users cannot just use the file name when reading files. They will have to specify an absolute file name (problematic) or a filename relative to something they might not control (also problematic).

The result is confusion and friction.

## Example

I'm running on our jupyter hub. The notebook can run. Voila can run. Panel Jupyter Preview cannot run.

![image](https://user-images.githubusercontent.com/42288570/131513962-b2a455f4-2ca5-4fec-a000-fe35ae718948.png)

## Solution

Run the notebook app from the folder of the notebook when started using Panel Jupyter Preview.

**Comment by philippjfr** [comment]
Should be possible to temporarily switch the current directory while the application executes.

**Comment by jbednar** [comment]
This seems very tricky, because normally Jupyter can only "see" files in the directories in or below where it was launched. If you want to access anything shared between multiple directories (as we do for the various HoloViz examples/ directories like `user_guide` and `getting_started`), you have to start Jupyter at a directory level *above* where the notebook is, to allow notebooks to use "upward" paths relative to the notebook to find any such shared files. I'd be worried that if you switch the current directory such carefully curated behavior will break. But since @philippjfr knows about all this already, I assume he's proposing something that wouldn't break it...

**Comment by philippjfr** [comment]
Jupyter can see anything, the UI just won't show it.

**Comment by philippjfr** [comment]
The new Jupyter server extension (added in 0.14) now runs the app in an isolated kernel that runs in the appropriate path so this is fixed.
