### ISSUE TITLE
panel.Param widgets add toggle on parameterized objects even if `expand = False`?

### ISSUE THREAD

**Issue by EmperorDali** [holoviz/panel#2927]
I'm not sure if I'm understanding the logic of `Param.widget()` correctly, but the conditional that decides to return either the lone widget or the widget with a toggle button (presumably to expand this object and show subparams?) seems to be gated incorrectly.

https://github.com/holoviz/panel/blob/25bab759e38a92bfcbfce167ecfeca301da015da/panel/param.py#L559

It seems that the second line of this if statement should be:

`and (self.expand_button or (self.expand_button is None and self.expand))):`

Looking at this further - what's the purpose of the generated `Toggle` button? It doesn't seem hooked up to any callbacks?

**Comment by jbednar** [comment]
The logic is convoluted, but as far as I can see it's correct. It's trying to determine whether we need to add a "..." button that lets the user decide whether to show or hide a subobject's parameters. There are two cases where such a button is needed:

1. If `expand_button` (normally None) has been forced to True by a user. In this case, we respect the user's wishes, and always add an expand button. Otherwise we'll need to guess the user's intent, so we consider if case 2 applies.
2. If the user has _not_ forced `self.expand_button` to True or False, _and_ the user has also not forced subobject parameters to be expanded automatically by setting `expand=True`, then users may want to see subobject parameters, so we'll guess that there should be an expand button.

If we followed your suggested change, there would be an expand button precisely when we don't actually need it, i.e. when the subobject parameters have already been expanded, and not when we do need it so that users can reveal the subobject parameters if they wish. 

One could of course want to provide the ability to hide the subobject parameters even if they are initially shown, which is why users are allowed to force `expand_button` to True, but since there is not much point in providing the ability to hide subobject parameters once they've already taken up screen real estate, the button is not added by default in that case. Tricky, huh?

You can see the expand button in use at https://panel.holoviz.org/user_guide/Param.html#parameter-subobjects , where it does function to show or hide the subobjects parameters if you run the underlying notebook or click on the Binder link.  I would think that the expand button would be able to work even without Python, since the underlying widgets can work using JS callbacks, and indeed were the expand button to be hooked up in JS the website would be far less confusing.  Happy to accept a feature request to create such a Python-independent binding for that button!

**Comment by philippjfr** [comment]
>I would think that the expand button would be able to work even without Python, since the underlying widgets can work using JS callbacks, and indeed were the expand button to be hooked up in JS the website would be far less confusing. Happy to accept a feature request to create such a Python-independent binding for that button!

I mean I'm not sure I'd accept such a pull request, Param is really primarily a Python based system and while it might be nice for the website to be able to demo the expand button for practical purposes this would add relatively little value since none of the callbacks attached to the parameters would actually function. It would also add some cost which is that we'd always have to construct these widgets, send them to the client-side etc.

**Comment by jbednar** [comment]
I'll defer to your judgement about the cost, which indeed may be prohibitive, but the reason I think this is a worthwhile feature is that while people can add JS links and embed state and do other things that work with widgets without Python, if they can't expose the widget in the first place then such functionality won't work. Definitely if the coding cost is high then it's not worth doing, because people can always force `expand=True` and avoid the issue altogether.

**Comment by philippjfr** [comment]
Personally I don't think it's worth it, but please open an issue if you think really think that's a worthwhile feature. Since that's not really the topic of this issue, I'll close this particular issue.
