### ISSUE TITLE
Example in readme not found

### ISSUE THREAD

**Issue by HenriqueAJNB** [holoviz/panel#3077]
Just click on the link pointing to `Portifolio Optimizer` at `readme.md` and a `404 - Page not found` is shown.

**Comment by jbednar** [comment]
If that's a link pointing to https://portfolio-optimizer.pyviz.demo.anaconda.com/portfolio , the deployed examples were down today due to an expired certificate and needed to be restarted to pick up the new certificate. I'll close this as the link is working now, but feel free to reopen with more detail if that's not the link you meant.
