### ISSUE TITLE
Add sync_location argument to .servable of widgets

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#3088]
I'm trying out setting the `template` in the `pn.extension`.

I can see that one thing that would make it very easy to create very powerful applications would be to provide `sync_location=True` to widgets in the `.servable` function.

```python
import plotly.express as px


def plot(count):
    x = [str(i) for i in range(0, count)]
    y = list(range(0, count))
    return px.bar(x=x, y=y)


import panel as pn

pn.extension("plotly", sizing_mode="stretch_width", template="fast")

count = pn.widgets.IntSlider(name="Count", start=10, end=50, value=10).servable(area="sidebar")
pn.panel(pn.bind(plot, count)).servable(title="Slider Example", area="main")
```

Just think about how powerful and easy to explore with colleagues the application would be if it synced the value of `count` to the url via

```python
count = pn.widgets.IntSlider(name="Count", start=10, end=50, value=10).servable(area="sidebar", sync_location=True)
```

Maybe `sync_location` should be `sync`, `sync_value`, `url_parameter`, `url` or similar.

**Comment by philippjfr** [comment]
Hmm, that would be purely syntactic sugar since it's effectively equivalent to: 

```python
count = pn.widgets.IntSlider(name="Count", start=10, end=50, value=10).servable(area="sidebar")
pn.state.location.sync(count)
```

I think there's probably an issue with a lack of discoverability of the location syncing but I'm not 100% convinced that adding syntactic sugar into the `.servable` method makes sense, especially since it's kind of useless if you want to add a whole `Column` of widgets into the sidebar for instance. Opinions welcome here.

**Comment by MarcSkovMadsen** [comment]
I think there are many, many things that are more important. Lets close this one. Feel free to reopen if you (whoever you are) would like this too.
