### ISSUE TITLE
Add docstrings and parameter docstrings where missing

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#3131]
Looking at the code while trying to autogenerate type stubs I realized that docstring are missing in a lot of places.

For example in in panel.widgets.slider

![image](https://user-images.githubusercontent.com/42288570/150634457-7bae5797-cdd2-4f09-863d-01f126e4a8a2.png)

This makes using Panel more difficult than it has to be.

When adding the docs I would recommand adding a link in the class docstring to the reference guide if it exists. This will make navigation and learning so much easier.

## Example

Adding the class string 

![image](https://user-images.githubusercontent.com/42288570/150634501-da83a0c9-586b-4207-986d-fcf646aa023a.png)

would enable me to navigate the docs much, much quicker

![image](https://user-images.githubusercontent.com/42288570/150634552-90bce52d-807a-4169-9dab-d7b99c096c6d.png)

than today

![image](https://user-images.githubusercontent.com/42288570/150634623-981f46bb-b9b9-408b-82a6-d48b18aceb8e.png)

@maximlt . I believe you would agree here :-)

**Comment by jbednar** [comment]
Adding docstrings would be an excellent task for someone to take on; indeed, they are sorely missed! But I don't think it would be appropriate to add links to the reference guide into the docstrings as above, because for one thing the reference guide is _generated_ from the docstrings (and inspection). The reference guide would then be linking to itself when it is generated. Plus tying each class to a particular URL like that seems unlikely to be something we could keep up to date and consistent. But I _think_ we could provide some mechanism where a Param-based library registers a base URL for a superclass and then the appropriate URL could be generated and appended to the docstring as the class is created, which would ensure that it's done consistently.

I'd also like each of our Reference Gallery items to include the output of `help(obj)` for that obj, since that's typically complementary information that too few people know about.

**Comment by maximlt** [comment]
Also +1 on the docstrings of course!

And as for the URL, my first reaction was no because I don't think this is
very common and maybe not so easy to maintain. But giving it more thoughts
it could be a great idea. Panel is not a traditional Python library, it's
very visual. When I write code that uses Panel I spend a lot of time in the
reference gallery, to get a better impression of how a component works and
what I can do with it. Take the example of the Tabulator widget, there's no
way its docstring could describe all the things you can do with it.

@jbednar Marc added a like to the reference gallery, that is manually
crafted. Not the API reference which is indeed automatically generated (I
never have a look at this page, there's usually enough information in the
reference gallery. If not, I directly look into the code but that may be a
little unusual for a user).

Le sam. 22 janv. 2022 à 18:55, James A. Bednar ***@***.***> a
écrit :

**Comment by jbednar** [comment]
Oh, by "reference guide" he meant "reference gallery", not the reference manual (API)? Indeed, a reference gallery link would be more difficult to auto-generate, and only rarely exists, so it does make sense to add that manually.

**Comment by MarcSkovMadsen** [comment]
I really think we should invest in adding better docstring to the code.

Check out how cool and helpful the package can appear in a modern editor or IDE.

![image](https://user-images.githubusercontent.com/42288570/150667696-0272a1df-bf2f-47ce-b156-7774a0de06b5.png)

if you add

![image](https://user-images.githubusercontent.com/42288570/150667711-400cac8b-a6a5-465e-9725-177a6611806a.png)

Before it was

![image](https://user-images.githubusercontent.com/42288570/150667734-b52b14a3-0083-43dd-9b83-755be5aa7c9e.png)

**Comment by MarcSkovMadsen** [comment]
Just storing a gif to illustrate that I will be using in a docstring example

![my-panel-app](https://user-images.githubusercontent.com/42288570/150682339-6e97b1a1-c1f8-4a70-9c58-893769510ef4.gif)
.

**Comment by MarcSkovMadsen** [comment]
You can actually achieve something like

https://user-images.githubusercontent.com/42288570/150686319-200d4225-ad00-4f5a-ba74-2882bfb11462.mp4

by adding

something like

```python
"""# Panel is a high level app and dashboarding framework

Works with the tools you know and ❤️. Welcome to our community 👪

- Get Started: https://panel.holoviz.org/
- Join the Community: https://discourse.holoviz.org/
- Contribute: https://github.com/holoviz/panel

Follow us on [Twitter](https://twitter.com/Panel_org) or [LinkedIn](https://www.linkedin.com/company/79754450).

## Interactive models with `.bind`

![Interactive Model App](https://user-images.githubusercontent.com/42288570/150685744-2d1c654a-fa6c-4e00-91c0-a2712afcd647.gif)

You can use Panels `.bind` to bind your models to widgets.

```python
import panel as pn

color = "#C43F66"

pn.extension(sizing_mode="stretch_width", template="fast")


def model(a, b, emoji):
    result = "#" + (emoji * a) + " + " + (emoji * b) + " = " + (emoji * (a + b))
    return result

pn.pane.Markdown("## Input", margin=(5, 10)).servable(area="sidebar")
input1 = pn.widgets.RadioButtonGroup(value=1, options=[1, 2, 3], button_type="success", name="A").servable(area="sidebar")
input2 = pn.widgets.IntSlider(value=2, start=0, end=3, step=1, margin=(20, 10)).servable(area="sidebar")

interactive_add = pn.bind(model, a=input1, b=input2, emoji="⭐")
pn.panel(interactive_add).servable(area="main", title="My interactive MODEL")

pn.state.template.param.update(site="Panel", accent_base_color=color, header_background=color)
```

You can serve your app via

```bash
$ panel serve 'script.py' --autoreload
2022-01-23 15:00:31,373 Starting Bokeh server version 2.4.2 (running on Tornado 6.1)
2022-01-23 15:00:31,387 User authentication hooks NOT provided (default user enabled)
2022-01-23 15:00:31,389 Bokeh app running at: http://localhost:5006/script
```

The file can be a `.py` script or `.ipynb` notebook.

Try changing the return value of the function. Panel will magically ✨ understand how to show the 
objects you know and ❤️. 

This includes 
[Bokeh](https://panel.holoviz.org/reference/panes/Bokeh.html#panes-gallery-bokeh), \
[HoloViews](https://panel.holoviz.org/reference/panes/HoloViews.html#panes-gallery-holoviews), \
[Matplotlib](https://panel.holoviz.org/reference/panes/Matplotlib.html#panes-gallery-matplotlib) and \
[Plotly](https://panel.holoviz.org/reference/panes/Plotly.html#panes-gallery-plotly) figures.

## Interactive dataframes with hvplot `.interactive`

![Interactive DataFrame App](https://user-images.githubusercontent.com/42288570/150683991-9cece6a1-3751-42d2-8256-505f5deb12be.gif)

You can use [hvplot .interactive](https://hvplot.holoviz.org/user_guide/Interactive.html) to make 
your dataframes interactive.

```python
import panel as pn
import pandas as pd
import hvplot.pandas

color = "#0072B5"
df = pd.DataFrame(data={"x": [0, 1, 2, 3, 4], "y": [0, 2, 1, 3, 4]})

pn.extension(sizing_mode="stretch_width", template="fast")

pn.pane.Markdown("## Selection", margin=(10, 10)).servable(area="sidebar")
count = pn.widgets.RadioButtonGroup(value=5, options=[3, 4, 5], name="Count", button_type="success").servable(area="sidebar")

interactive_df = df.interactive().head(n=count)
pn.panel(interactive_df.panel(height=200)).servable(area="main")

interactive_plot = interactive_df.hvplot(x="x", y="y").opts(line_width=6, color=color)
pn.panel(interactive_plot.panel(height=200)).servable(area="main", title="My interactive DATAFRAME")

pn.state.template.param.update(site="Panel", accent_base_color=color, header_background=color)
```

For more about hvplot `.interactive` check out this [blog post](https://towardsdatascience.com/the-easiest-way-to-create-an-interactive-dashboard-in-python-77440f2511d1).
"""
```` 

to the `__init__.py` file.

**Comment by MarcSkovMadsen** [comment]
You can even achieve something like

![panel-docstrings](https://user-images.githubusercontent.com/42288570/150687335-57026641-e62c-48c4-9169-1cd2b233cb58.gif)

**Comment by maximlt** [comment]
Ok so VSCode can render docstrings formatted in markdown. Does anyone know if Pycharm can also do that? On the one hand this is nice, on the other I don't know if this plays well with autogenerated code documentation (with sphinx) for which I believe the docstrings have to be formatted in RST.

Anyway it's interesting to know Marc! I don't think I would add lots of information in the main docstring though, I would prefer users to have a look at the `Getting started` page instead of that, and focus on improving that page if need be. A few links link at the top of your example would imo be useful.

**Comment by jbednar** [comment]
I am strongly in favor of using markdown in docstrings if there is any way to make that feasible, e.g. with a plugin to Sphinx.

**Comment by MarcSkovMadsen** [comment]
This is then how the documentation of `panel` looks in Jupyter. I think its better than not having anything (today) but would be nice if Jupyter could display markdown or ReST docstrings. See https://github.com/Quansight-Labs/quansight-labs-site/issues/301

![image](https://user-images.githubusercontent.com/42288570/151104140-eaef8024-9217-4b89-9f25-834736f730bd.png)

**Comment by philippjfr** [comment]
Would you consider this done now @MarcSkovMadsen ?

**Comment by MarcSkovMadsen** [comment]
The first iteration is done for widgets and panes. I have a plan to do it for layouts next. And probably for other things as well.

**Comment by MarcSkovMadsen** [comment]
Closing as docstrings have been added systematically to all Panel components.
