### ISSUE TITLE
FileInput widget without file loading (to only get the filename)

### ISSUE THREAD

**Issue by LaurensvanG** [holoviz/panel#3137]
#### Is your feature request related to a problem? Please describe.
I want to use the file selector of the FileInput widget because it's user friendly but I am loading unconventional datatypes. As such, it cannot decode the file and does not save the filename. I don't need it to, as I just want the filename and load it manually.

#### Describe the solution you'd like
A new FilenameInput widget that only provides the file selector and returns the filename, or an option for the FileInput widget to ignore the decoding step.

#### Describe alternatives you've considered
I am currently using the TextInput widget to manually input a filename but it is not very user friendly.

**Comment by maximlt** [comment]
What kind of data type are you trying to load? And how do you plan to load the data just from the filename?

**Comment by philippjfr** [comment]
This does not make much sense to me unfortunately. This would only work in a very, very narrow set of cases. Since the browser's file input works in the clients file system this would only work for apps deployed locally. That would not be **that** bad on its own but worse yet the browser only allows returning the file name (not the file path) so it would only work in the very use case where you are browsing files in the same directory you are serving the app from. I'm tempted to close with a wontfix tag but would be very open to other proposals for providing a nicer UI here. Does the [FileSelector](https://panel.holoviz.org/reference/widgets/FileSelector.html) address your needs?

**Comment by LaurensvanG** [comment]
Ah, I would in fact need to have the entire file path. Sorry to hear that's not possible. 

The FileSelector might be fine, I'd have to look into the details but the interface is a little less neat than I hoped to achieve. Nonetheless, thanks for looking into it for me!

**Comment by maximlt** [comment]
If the data you're loading is always in a specific folder then you could just on start-up parse the list of files it contains and use that list (or dict of filename: path) as the options of a `Select` widget.

You could also have a look at this Bokeh thread (https://discourse.bokeh.org/t/select-a-folder-with-bokeh/8225/2) with someone having a similar need as yours, that found a workaround with using Tkinter.

I'm going to close this issue, since I don't think obtaining the filename only would be very useful to most users.

(Still curious about the kind of data you were trying to load with the FileInput? Were they heavy files?)

**Comment by LaurensvanG** [comment]
I want the user to able to select any file so that won't work. I think I'll either keep the TextInput or make a FileSelector popup or something (it is a bit too big for a sidebar widget).

Ah sorry! I forgot to answer that question. I am opening `.fsm` spectral files from Perkin Elmer, which are around 1GB, generally. I am not sure if they would not load at all or if it just took a long time. But I don't know how to parse the files myself anyways. I am using a module from the brilliant PyMca toolbox to load it manually.

**Comment by maximlt** [comment]
1G is very likely too much anyway for the `FileInput` widget, that may explain why you never got the filename. In the next release of Panel the docs will include a section of the limitations of this widget, you can take a sneak peek at this here: https://github.com/holoviz/panel/blob/master/examples/reference/widgets/FileInput.ipynb
