### ISSUE TITLE
MultiChoice unfolds upwards, obscured by header

### ISSUE THREAD

**Issue by vp-code** [holoviz/panel#3218]
When using a MultiChoice widget with a template, if the number of options is moderately large, the choices are displayed upwards and get obscured by the header, destroying user readability. Minimum working example, panel version 0.12.6:
```
#!/usr/bin/env python
import panel as pn
pn.extension()

Fruits = ['Apple', 'Banana', 'Pear', 'Strawberry','Orange','Mango','Guava','Blueberry','Raspberry']
multi_choice = pn.widgets.MultiChoice(name='MultiSelect', value=['Apple'],options=Fruits)
pn.template.VanillaTemplate(
    title="Vanilla",
    main=[multi_choice]
).servable()
```

**Comment by ingebert** [comment]
This could be related to the `position ` option of choices.js (used by Bokeh->Panel) set to `Auto`:
_"By default, if there is not enough space within the window the dropdown will appear above the input, otherwise below it."_
[https://github.com/Choices-js/Choices#position](url)
As a workaround I set the standard option value of `position` to `bottom` within this file:
[..\Lib\site-packages\bokeh\server\static\js\bokeh-widgets.min.js](url)
It might be hard to find, some of those strings might help:
`...searchResultLimit:4,searchFields:["label","value"],position:"bottom",resetScrollPosition:!0...`

**Comment by philippjfr** [comment]
Fixed on main thanks to the update to bokeh 3.x.
