### ISSUE TITLE
Warn when bound function without any parameter arguments is passed to Param{Method|Function}

### ISSUE THREAD

**Issue by ahuang11** [holoviz/panel#3439]
After not touching panel for a bit and trying to help out on Discourse, it took me longer than I should have to realize the reason it was not updating was because I was missing `.param` before `dmap = hv.DynamicMap(pn.bind(plot, tabulator.selection))`. 

Should pn.bind realize that it's binded to a value, not a param type, and raise a warning?

```
import panel as pn
import pandas as pd
import holoviews as hv

pn.extension("tabulator")

df = pd.DataFrame(data={"x": [0, 5, 10], "y": [0, 3, 10]})

def plot(index):
    return hv.Scatter(df.iloc[index], "x", "y").opts(xlim=(0, 10), ylim=(0, 10), size=10)

tabulator = pn.widgets.Tabulator(df)
dmap = hv.DynamicMap(pn.bind(plot, tabulator.selection))

pn.Row(tabulator, dmap)
```

To get it working:
```
dmap = hv.DynamicMap(pn.bind(plot, tabulator.param.selection))
```

**Comment by MarcSkovMadsen** [comment]
The problem is that `pn.bind` supports binding to (constant) values as well. So it would not know whether doing so was the intention or not.

**Comment by maximlt** [comment]
Right Marc, although in this particular example only a single value is bound which is pretty much a no-op. I guess in that case I'd make sense to emit a warning, or even raise an error. But when there's more than one thing bound, I don't think we can do much.

**Comment by jbednar** [comment]
I think the usage illustrated there is completely legal and one that I would use for debugging, e.g. to force a fixed value while I work on other things. So I think this just has to be a matter of better documentation; the actual behavior for this example is correct and should not warn.

**Comment by ahuang11** [comment]
Is there any other reason other than debugging to set a fixed value? If not, I think it would make sense to still raise a warning.

**Comment by jbednar** [comment]
Sure; `pn.bind` is a fully general widget-aware replacement for https://docs.python.org/2/library/functools.html#functools.partial , and _all_ `partial` does is accept constants, so binding to constants is indeed useful in general. For instance, if you are wrapping some function you didn't write, often it will have some arguments that you want to set to a value but don't necessarily want to create a widget for. `pn.bind` lets you do that. If you are *only* using constants in that call, then you could have used `partial` instead, but because `pn.bind` can be chained, just as `partial` can, I'm not comfortable assuming that any particular call is an error; it's totally legal and appropriate to call it once to bind some values to constants, and again to bind some values to widgets. Why make people learn about and import `partial` when `bind` already does that? I think binding constants to arguments is a general and valuable pattern to encourage, not something that we should be treating as an error.

**Comment by philippjfr** [comment]
Thanks for the detailed answer @jbednar. I do agree that passing in fixed values is fully reasonable and accepted usage both for debugging and in practice. Having to do run separate `pn.bind` and `partial` calls just to pass in fixed values would be pretty ugly. I do see the argument around warning when passing in **only** fixed values but on balance I think this is indeed useful for debugging. If anyone does think strongly that is the right way to go I'd be persuaded but on balance that is only a very narrow fix for the underlying problem. I think the way forward is doing a much better job at explaining param in the Panel documentation as that is where a lot of the confusion comes from.

**Comment by philippjfr** [comment]
Thinking about this some more the potentially better fix would be to warn when a function with no dynamic parameters bound to it is passed to `hv.DynamicMap` and `panel.param.Param{Method|Function}`. This would catch the issue without needlessly degrading the utility of `pn.bind`.

**Comment by philippjfr** [comment]
So in the case of Panel that would look something like this:

<img width="1447" alt="Screen Shot 2022-04-24 at 16 59 58" src="https://user-images.githubusercontent.com/1550771/164982704-17e1fa87-c657-4f4e-a4ef-e3ad036b721c.png">

Would of course have to be implemented separately for HoloViews.

**Comment by jbednar** [comment]
Good point; I think it's safe to catch it at that point, and indeed that would normally be a misunderstanding or an error. Since this warning has an explicitly educational purpose, I'd suggest being more verbose even, with an example of correct and incorrect usage (foo vs foo.param).
