### ISSUE TITLE
Cannot see pictures for Custom Components guide

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#3753]
I'm looking at https://panel.holoviz.org/user_guide/Custom_Components.html and cannot see the pictures

![image](https://user-images.githubusercontent.com/42288570/184470600-46fb13e5-e385-4d34-84b1-26b3b41f4a2b.png)

The issue is that urls like https://picsum.photos/800/300?image=0 are not secure and thus my enterprise restricts the access.

Please host these 3 pictures on a secure location.

**Comment by philippjfr** [comment]
It's not just the three pictures though, it's a whole series of them (to drive the slideshow). I also don't know why your enterprise is so strict, picsum.photos has SSL enabled and is a perfectly standard website that is even sponsored by DigitalOcean.

**Comment by philippjfr** [comment]
If you can find a similar resource for stock pictures I'd be very happy accepting a PR here. However we can't be responsible for screening perfectly safe content because it might be blocked by some corporate VPN, indeed there's no way for me to do so. If I were to select another source there's every chance your enterprise restrictions would also apply to it.
