### ISSUE TITLE
Attempt to integrate ipywidgets bokeh into panel

### ISSUE THREAD

**Issue by govinda18** [holoviz/panel#4167]
#### Is your feature request related to a problem? Please describe.
Currently a lot of logic is same between panel's Ipywidget model and ipywidget bokeh. This requireies any changes made at either of the places to be synced to the other place. A good example is this commit https://github.com/holoviz/panel/issues/3915 that ideally needs to be patched to ipywidget_bokeh as well.

#### Describe the solution you'd like
As discussed yesterday, it may be worth an attempt to move ipywidgets_bokeh into panel instead. This will reduce code duplication and improve maintenance as well.

#### Describe alternatives you've considered
As of now, I have to manually sync the two to internally make sure that things are in sync between jupyter and standalone dashboard.

Not sure how much effort this is and if this is even feasible. Logging this for starting the discussion.

**Comment by philippjfr** [comment]
Thanks for writing this up @govinda18. Thinking about this again there is basically zero chance that we will move the ipywidgets_bokeh model into Panel because including the Jupyter dependencies would increase the Panel.js bundle size by several megabytes. Similarly moving the simplified model that we use in Panel into ipywidgets_bokeh is also not sensible because you will end up loading the ipywidgets_bokeh JS bundle even if it's not necessary (and will lead to issues like this https://github.com/bokeh/ipywidgets_bokeh/issues/65).

Therefore, as annoying as it is, we have to keep both implementations. We can consider porting the change in #3915 to ipywidgets_bokeh or simply wait for the Bokeh 3.0 update which will make layout invalidation entirely unncessary.
