### ISSUE TITLE
Azure Oauth2.0 With AD Access ("Refresh Token")

### ISSUE THREAD

**Issue by VedoBlaze** [holoviz/panel#4223]
Hi, 

We are using this custom plugin but are getting a issue when calling the Azure platform 2.0 OAuth. 
The issue we are getting is 
"ERROR: panel.auth - AzureAd OAuth provider returned a HTTP 400: Bad Request error. The full response was: {'error': 'invalid_grant', 'error_description': 'AADSTS54005: OAuth2 Authorization code was already redeemed, please retry with a new valid code or use an existing refresh token.\r\nTrace ID: ff5daa04-a393-4bfc-9cfd-1ae511fb3e00\r\nCorrelation ID: e78f94a1-90d9-41d5-a7a1-221238ffa5b2\r\nTimestamp: 2022-11-29 14:30:03Z', 'error_codes': [54005], 'timestamp': '2022-11-29 14:30:03Z', 'trace_id': 'ff5daa04-a393-4bfc-9cfd-1ae511fb3e00', 'correlation_id': 'e78f94a1-90d9-41d5-a7a1-221238ffa5b2'}"

Through some error searching we have navigated that the solution is in enabling a way in getting refresh tokens. LInk below: 
https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow#refresh-the-access-token

Is hit something you can implement so that we can further use panel? 

Thanks in advance for you contribution.

**Comment by shkarlsson** [comment]
I suppose we're looking for a way to save the refresh token from the first auth response and then re-use it in subsequent requests that session. @VedoBlaze, please specify if necessary.

@philippjfr, I see you are very active on this repo and was hoping you could help us resolve this. Is this something that could be supported in Panel? If it's not reasonable to build it into Panel, would it be possible to get some guidance on how to implement this in _our_ setup?

Thanks!

**Comment by philippjfr** [comment]
Yes, I can investigate this. To be very clear under what conditions does this error occur exactly? On initial page load or are you trying to make requests to Azure APIs after the application is loaded? If you could provide as much detail as possible for me to reproduce this that would be great.

**Comment by philippjfr** [comment]
@shkarlsson I've now made the `refresh_token` available in OAuth. If you could I'd appreciate it if you could try the PR. To do so check out the repo, then run `pip install -e .` (make sure you have nodejs available) and then run `panel build panel`. That should be sufficient for testing.

**Comment by philippjfr** [comment]
I'll probably go ahead and merge it and cut a dev release you can test.

**Comment by philippjfr** [comment]
Thanks @xnsde. Would love to chat to figure out what exactly is needed here. Based on those docs my understanding was that in general a refresh token is valid for 24 hours, and didn't see any reference to them being single-use.

**Comment by MarcSkovMadsen** [comment]
Hi @xnsde 

Since you can use Panel to execute javascript scripts I believe you can update secure cookies through the web socket. There are many ways to invoke javascript scripts.

For [awesome-panel.org/sharing](https://awesome-panel.org/sharing) I needed the [optional (github) oauth for public apps](https://github.com/holoviz/panel/issues/3960). I could not see how to use Panels built in OAuth to support this use case. So I built my own Github OAuth component inspired by Panels OAuth and using [ReactiveHTML](https://panel.holoviz.org/user_guide/Custom_Components.html#reactivehtml-components). You can find the component [here](https://github.com/awesome-panel/panel-sharing/blob/main/src/panel_sharing/components/oauth.py) for inspiration.
