### ISSUE TITLE
My browser keeps old version of (dev) docs - even through hard refresh

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4682]
I'm on Windows trying to improve the `dev` docs. I notice that in both Edge and Chrome browsers an old version of the `dev` home page is kept. 

- If I go to the `dev` docs or refresh the `dev` docs, I get the old version.
- If I hard refresh the `dev` docs, I get the new one. But only until I refresh again.

Thus I can toggle between old and new docs as shown below. If this behavior is also there when deployed to `production` nobody will see the new docs.

https://user-images.githubusercontent.com/42288570/233816495-205a0c03-0c87-4f36-ad55-8ceb3e23aa3c.mp4

**Comment by philippjfr** [comment]
This behavior is intentional and is what allows caching of pyodide across sessions. The cache is automatically busted by version bumps so I do not consider this a major issue. For dev builds we could add the git commit SHA to the cache key though so it's not a hard thing to fix. For now you can easily just clear out the cache:

<img width="846" alt="Screen Shot 2023-04-23 at 11 30 41" src="https://user-images.githubusercontent.com/1550771/233831615-5fdb35af-c4d3-4654-918d-93a0b90ddf69.png">
