### ISSUE TITLE
Styling of Perspective scrollbar makes it invisible

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4997]
I'm on Panel 1.0.3.

I'm trying to use Perspective. It seems some non Perspective scrollbars with a bad styling takes over instead of the nicely styled Perspective scrollbars.

```python
import panel as pn

pn.extension("perspective", sizing_mode="stretch_width", template="fast", theme="dark")
data = {"x": [1] * 100, "y": [1] * 100}
pn.pane.Perspective(data, height=400, theme="material-dark").servable()
```

On the right I would expect it to be clear where I should click and drag from. But its not

![image](https://github.com/holoviz/panel/assets/42288570/a1d5cdc5-9e66-4f82-a284-0d57484a9398)

If you use the Perspective toolbar at the bottom to change the theme to material-light you get a nice looking scrollbar when you hover over Perspective

![image](https://github.com/holoviz/panel/assets/42288570/192f5403-cfa2-4eda-9f27-0c22ed930eb3)

You can also change back to the material-dark theme and the scrollbar is still nice and useful on the right

![image](https://github.com/holoviz/panel/assets/42288570/f3c04ab4-424b-4bd5-b459-35011969dd6e)

I believe this is a regression and used to work nicely.

**Comment by philippjfr** [comment]
Appears fixed by the Perspective upgrade:

<img width="1502" alt="Screenshot 2024-03-12 at 01 34 32" src="https://github.com/holoviz/panel/assets/1550771/1e1ed860-c9ee-49ad-ad4c-e961da0a2467">

<img width="1498" alt="Screenshot 2024-03-12 at 01 35 33" src="https://github.com/holoviz/panel/assets/1550771/cf9e9050-a696-4cfd-afe6-c43eaadaa0c0">
