### ISSUE TITLE
wrong units for DateRangeSlider step

### ISSUE THREAD

**Issue by jorgeperezg** [holoviz/panel#4999]
I am on panel 1.04 and python 3.11.3

#### Description of expected behavior and the observed behavior
The units of DateRangeSlider are expected to be ms (https://panel.holoviz.org/reference/widgets/DateRangeSlider.html) but they are days.

#### Complete, minimal, self-contained example code that reproduces the issue

```
from datetime import datetime

import panel as pn


t0 = datetime.fromisoformat("2023-01-01")
t1 = datetime.fromisoformat("2023-02-01")
dt = 1

tlim = pn.widgets.DateRangeSlider(start=t0, end=t1, step=dt, value=(t0, t1), name="Time limits")
tlim.servable()

```

**Comment by Hoxbro** [comment]
This behavior was changed upstream in https://github.com/bokeh/bokeh/pull/12212.

A PR to update the docs with the new behavior will be welcomed.

**Comment by axxeny** [comment]
The units of days are now considered to be the expected behaviour by both `panel` and `bokeh` (as per comment below). It is also already reflected in the documentation [by this commit](https://github.com/holoviz/panel/commit/8080eec3a16ff75b25f01953db0a462f3ad3b6d8), therefore I believe this ticket can be closed.
