### ISSUE TITLE
Unnecessary scroll bar when using Column

### ISSUE THREAD

**Issue by aditya3434** [holoviz/panel#5544]
When rendering panel column with multiple row in Jupyter Lab/Notebook, a redundant scrollbar shows up even though there appears to be no overflow. 

#### ALL software version info
Panel version 1.2.x and Bokeh version 3.x

#### Description of expected behavior and the observed behavior
Expected behavior : All components rendered without scrollbar
Actual behavior: A scrollbar is displayed even though there is no overflow

#### Complete, minimal, self-contained example code that reproduces the issue

```
import panel as pn
pn.extension()

pn.Column(pn.Row(pn.pane.HTML("My panel")), pn.Row(pn.widgets.Button(name='Click me', button_type='primary'), pn.widgets.IntSlider(start=0, end=10, value=5)))
```

#### Stack traceback and/or browser JavaScript console output
No stack traceback or console error

#### Screenshots or screencasts of the bug in action
![Animation](https://github.com/holoviz/panel/assets/56246494/d29f0405-ea4d-48b0-936e-5cb09b2553aa)

- [ ] I may be interested in making a pull request to address this

**Comment by maximlt** [comment]
Hi @aditya3434 and thanks for this clear bug report 👍 

I believe this is problem was due to the invisible scroll button and was fixed in https://github.com/holoviz/panel/pull/5532.
![image](https://github.com/holoviz/panel/assets/35924738/4fc424c5-7be5-44bc-bd32-db8748446c52)

I'm going to close this issue, feel free to comment in the issue if it's not fixed in the next release.
