### ISSUE TITLE
Thumbnail for Reactive Expressions is missing

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#5885]
![image](https://github.com/holoviz/panel/assets/42288570/8094cccc-b2ce-4f44-8929-aad1bf17245f)

**Comment by philippjfr** [comment]
Already fixed, just needs a rebuild. Note the bug label should not be used for docs issues.

**Comment by MarcSkovMadsen** [comment]
I'm sorry about the docs bug. Its just so natural and logical to do this. I don't care if a defect is in software or documentation.

How can I then mark a doc defect in a way that its clear its a defect and not a feature request?

**Comment by philippjfr** [comment]
No need to be sorry. The bugs label just happens to be the most important label for prioritization. Maybe I'm too grumpy about that and it doesn't add much noise in the grand scheme of things. I'll think about it and then maybe we discuss a sensible tagging scheme and clean up existing tags again in the near future. In this case it wasn't even anything that required any commits or real action to be fixed in the next release.
