### ISSUE TITLE
param types vs panel widgets

### ISSUE THREAD

**Issue by poplarShift** [holoviz/panel#620]
The docs (https://panel.pyviz.org/user_guide/Param.html) tell us that
> internally Panel maintains a mapping between parameter types and widget types.

I think it would be helpful if we could explicitly list this mapping in the docs, i.e. which widget a given param type is translated to.

**Comment by jbednar** [comment]
Sounds like a good idea.  Rather than list the actual mapping, which would probably quickly go out of date, we should probably just explain how to list what the mapping is.  E.g. this would currently work from the command line:

```
python -c 'from panel.param import Param ; print(Param._mapping)'
```

But that's accessing a private class attribute, so maybe we should provide a public method for showing the current mapping.

**Comment by maximlt** [comment]
Hi!
I believe that it'd be indeed useful to have access to this private mapping and to document how to access it. I've had to dig the code a few times to try to understand why I was getting such that widget for that type of parameter.

Could it be as simple as ``panel.param.mapping()`` returning ``_mapping`` ?

**Comment by philippjfr** [comment]
Yeah, making `panel.Param.mapping()` public is fine with me.

**Comment by MarcSkovMadsen** [comment]
Just fyi. When i have a package of material widgets i would really like to be able to also Update the mapping.

I think that would be a future use case.
