### ISSUE TITLE
Textbox style widgets have unexpected behavior with JupyterLab 4

### ISSUE THREAD

**Issue by divyansshhh** [holoviz/panel#6314]
#### ALL software version info
Panel v1.3.0

### Description of expected behavior and the observed behavior
Create and run the following snippet in a notebook in JupyterLab 4 - 
```python
import panel as pn
pn.extension()
text_input = pn.widgets.TextInput(name='Text Input', placeholder='Enter a string starting with "A" or "B" here...')
text_input
```
When a character like 'A' is pressed (which is also a JupyterLab shortcut for "create cell above current cell"), we observe that the JupyterLab shortcut gets triggered and the textbox doesn't receive the input. 

### Screenshots or screencasts of the bug in action
![Panel-textbox](https://github.com/holoviz/panel/assets/30082866/7031f855-01ff-43e7-a2b1-beda82651398)

**Comment by krassowski** [comment]
This is related to a change in JupyterLab 4.1. Previously the focus in "command mode" would be placed on the notebook HTML node, which was causing unexpected scrolling when navigating with keyboard and made the notebook inaccessible because the [tabindex](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex) was lost after every cell operation.

In JupyterLab 4.1 this was fixed with cells retaining the focus even when their editor is not focused (https://github.com/jupyterlab/jupyterlab/pull/14115). However this meant that shortcuts such as insert cell above (<kbd>A</kbd>) or insert cell below (<kbd>B</kbd>) needed to targeted individual cells rather than a focused notebook node. To prevent this from the exact thing that we see in this issue the selectors for commands were modified, e.g. `.jp-Notebook:focus.jp-mod-commandMode` → `.jp-Notebook.jp-mod-commandMode :focus:not(:read-write)` (as documented in extension migration guide, [here](https://jupyterlab.readthedocs.io/en/latest/extension/extension_migration.html#change-of-notebook-focus-handling-impacting-command-mode-shortcut-selectors))

The problem with with panel appears to be that the widget is nested in shadow DOM hence the `:focus:not(:read-write)` does not work. This might requires a change in JupyterLab itself.

**Comment by philippjfr** [comment]
Really appreciate you chiming in here @krassowski. Let us know if that fix is something we can help with.

**Comment by krassowski** [comment]
Thank you! We merged a fix on JupyterLab side 9https://github.com/jupyterlab/jupyterlab/pull/15774) and will release it in 4.1.2. A workaround in the meantime would be to wrap the output in a container with `data-lm-suppress-shortcuts="true"`.

**Comment by philippjfr** [comment]
Thank you so much!

>A workaround in the meantime would be to wrap the output in a container with data-lm-suppress-shortcuts="true".

Could I just apply this in the top-level div or would it have to be inside each shadow root?

**Comment by krassowski** [comment]
I think top level should work. I do not recommend it long term though as users may expect some lf the shortcuts to work anyways (and JupyterLab fix will be out on Monday).

**Comment by philippjfr** [comment]
Since this was fixed upstream and applying the shortcut override has potential unintended consequences I will close this and suggest users upgrade JupyterLab.

**Comment by ahuang11** [comment]
For people experiencing the same issue, try upgrading `pip install "jupyterlab>=4.1.5"`. If it still persists, try another browser.
