### ISSUE TITLE
Some Panel examples are redundant with pyviz examples

### ISSUE THREAD

**Issue by jlstevens** [holoviz/panel#713]
The [demos](https://github.com/pyviz/panel/tree/master/examples/gallery/demos) in this repo are redundant with the examples on [examples.pyviz.org](http://examples.pyviz.org) (e.g the [clifford](https://github.com/pyviz-topics/examples/blob/master/attractors/clifford_panel.ipynb) example).

As I understand it, topics like this should all exist on  [examples.pyviz.org](http://examples.pyviz.org) only and the `panel examples` command should not fetch topic notebooks.

**Comment by philippjfr** [comment]
That's the point, those examples aren't actually mirrored here they simply point to the examples on examples.pyviz.org.

**Comment by jbednar** [comment]
The clifford example wasn't actually in `demos`, it's in https://github.com/pyviz/panel/blob/master/examples/gallery/simple/clifford_interact.ipynb , and is redundant with the example in https://examples.pyviz.org/attractors/clifford_panel.html#gallery-clifford-panel .  I don't know if any other examples overlap like that.  I'll reopen because there is at least some redundancy, and these two copies have diverged a lot...

**Comment by philippjfr** [comment]
This has been resolved, we now ship all the examples linked in the gallery directly to ensure they are updated.
