### ISSUE TITLE
New data is not updated when panel apps served with pn.serve

### ISSUE THREAD

**Issue by sansal54** [holoviz/panel#7555]
I try to serve multiple apps with pn.serve. Apps is in same folder and they are each wrapped in functions separately. Apps get data from database. The issue here is that they fetch data only when server restarts. When I refresh web browser and when there is new data on db, I cant see the updated data.

**Comment by philippjfr** [comment]
Thanks for the issue, however without any code to look at it's impossible for me to say what's happening but this is definitely a usage question that should be posted on [our Forum](https://discourse.holoviz.org/). My suspicion is you're simply doing `pn.serve(my_panel_obj)` which means you're serving one shared copy of the app. You should wrap your component in a function such that Panel reloads it every time you visit the endpoint, i.e. instead of:

```python
pn.serve(pn.Row(...))
```

do this:

```python
def app():
    return pn.Row()

pn.serve(app)
```
