### ISSUE TITLE
Make Panel help text readable on Windows in Command Prompt and Git bash

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#836]
#### System Info

- Panel: 0.7.0
- Bokeh: 1.4.0
- Python: 3.7.4
- OS: Windows 8.1
- Browser: Chrome

#### Description of expected behavior and the observed behavior

I can see I can get very extensive "help" text from Panel functions. I would expect to be able to read this nicely on Windows. But I cannot.

It does not display nicely in IPython in a cmd.exe command prompt or in a Git Bash terminal integrated in VS Code.

![image](https://user-images.githubusercontent.com/42288570/70019091-74f26680-1588-11ea-83b9-696d4e9c8116.png)

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import panel as pn

help(pn.pane.PNG)
```

#### Workaround

For now a workaround is to display the text in a jupyter notebook

![image](https://user-images.githubusercontent.com/42288570/70018948-f8f81e80-1587-11ea-931f-836666c185ef.png)

**Comment by jbednar** [comment]
According to https://en.wikipedia.org/wiki/ANSI_escape_code , there is some support in Windows for these ANSI escape codes, but it depends on your terminal and OS version.  It sounds like it's enabled by default for Windows 10 nowadays, but you may have to specifically enable it or install software for Windows 8.1 (which is no longer supported by Microsoft, for what that's worth).

Enabling ANSI colors in VSCODE is probably independent of the OS involved; see https://stackoverflow.com/questions/42102657/bash-terminal-colors-in-integrated-terminal-in-vs-code

I can think of a few different options for addressing this in our code or docs:

1. Continue printing ANSI codes as we do now, but suggest in a FAQ that if users see them come out garbled, that they may need to use a different shell or install an extension for their current shell.
2. Never print ANSI codes, so that no user will see garbled output, at the expense of less-readable output on those systems that do support it.
3. Attempt to detect whether the system will support ANSI codes before printing them.  I would guess that there is no reliable or clean way to determine that, so I don't think it's feasible, but it would be nice to be wrong about it!
4. Provide a configuration option in our code to disable ANSI code printing, and document that in a FAQ.

**Comment by MarcSkovMadsen** [comment]
Thanks @jbednar .


If it works on Windows 10. Then I thinks it's not worth the effort to fix. I'm just stuck on Windows 8.1 for a few more month. And I guess most Windows users are on Windows 10 or will be leaving very soon.

**Comment by xavArtley** [comment]
I have windows 10 however if I use help cmd I get:
![image](https://user-images.githubusercontent.com/18531147/70065883-14951080-15ec-11ea-826b-e646379f9a12.png)

But if I print directly the __doc__ I get :
![image](https://user-images.githubusercontent.com/18531147/70065976-3393a280-15ec-11ea-9b88-fd6a2aa5cbe6.png)

**Comment by MarcSkovMadsen** [comment]
I think this can be closed.
