### ISSUE TITLE
Coverage ignoring code executed on import

### ISSUE THREAD

**Issue by philippjfr** [holoviz/panel#870]
So at some point we had a precipitous drop in coverage. I can't really explain it but it seems like it's no longer counting any code that was executed on import, which is pretty deceptive.

For example look at the coverage in this file: https://codecov.io/gh/holoviz/panel/src/master/panel/viewable.py#L6

@ceball do you have any what might be going on here?

**Comment by ceball** [comment]
I suspect it's something like the following (not proven exactly, but probably enough to know the fix should be in nbsmoke):
* pytest loads plugins at startup
* if nbsmoke is installed, it gets loaded as a pytest plugin
* nbsmoke depends on holoviews (and imports it if available I guess)
* holoviews depends on panel (and imports it if available I guess)
* panel is therefore already imported before coverage measurement begins

nbsmoke's dependency on holoviews is optional and actually slated for removal. But whatever, nbsmoke should presumably not be importing stuff until needed, or doing some other cleanup to be a better behaved pytest plugin. I've opened https://github.com/pyviz-dev/nbsmoke/issues/35

**Comment by philippjfr** [comment]
Thanks! That makes a lot of sense at least.

**Comment by ceball** [comment]
This is indeed fixed by making nbsmoke not import holoviews when nbsmoke itself is imported. Panel's coverage changes from 70% (https://travis-ci.org/holoviz/panel/jobs/625890005#L2459) to 85% (https://travis-ci.org/holoviz/panel/jobs/626417869#L2486) after delaying the hv import. Good job you noticed the drop! (Presumably that sort of drop should have been some kind of error in itself, but maybe during that period the coverage PR comments weren't working because of all the repo moves?)

I couldn't find any pytest(-cov) docs about this kind of issue for plugin authors. I should probably make a docs PR there, or open an issue.

I actually already have a similar problem in nbsmoke itself when measuring its own test coverage (https://github.com/pyviz-dev/nbsmoke/issues/26), which is probably why I had any idea what might be going on in this panel issue :) I have never been able to ensure that nbsmoke is not imported before coverage collection begins. Presumably this is because both nbsmoke and pytest-cov are pytest plugins, and I need to do something to make them work properly together during nbsmoke's tests. Or maybe I should measure nbsmoke coverage without using pytest. I've never had time to play around with it enough to get anything working...

**Comment by ceball** [comment]
(I'll make a new nbsmoke release tomorrow, probably. Should be just pushing a tag, but need to review and merge my PR first.)

**Comment by philippjfr** [comment]
Thanks @ceball
