### ISSUE TITLE
Should a css_id parameter similar to css_classes be supported?

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#911]
THIS IS A DISCUSSION. FEEL FREE TO JOIN.

When trying to develop more advanced style, layout and interactivity inspired by modern frameworks like bootstrap I often need to **select specific HTML elements**.

With Panel I can add `css_classes` like `plot`. Then I can use document.querySelector on for example `.plot` or maybe `div.bk.plot`.

Often times thats not really enough. I need to be very specific and then it would be nice to be able to use the id. I.e. select via `div.bk.plot#magic-plot-1`.

As far as I know I cannot set the id of an element like `pn.Column(“content”, css_classes=[‘plot’], css_id=‘magic-plot-1’)`.

A workaround is to set `pn.Column(“content”, css_classes=[‘plot’, ‘id-magic-plot-1’])`. But that feels sort of like a hack and you need to refactor examples found online to this style.

**Should it be possible to use a parameter called `css_id` similar `css_classes`?**

What do you think?

#### Additional Context

Right now my example use case is creating some general functionality for showing *modal* boxes and *maximizing plots*

```python
open_modal_button.js_on_click(
        code="""
var modal = document.querySelector(".modal");

modal.classList.toggle("closed");
"""
    )
```

The works as long as I only have one `.modal` to open. But as soon as I have multiple I would like to be able to distinguish between them using an id.

![image](https://user-images.githubusercontent.com/42288570/71539802-ec29d900-2941-11ea-9786-07880317bebf.png)

**Comment by MarcSkovMadsen** [comment]
If added the then *reactivity* should be supported. 

I.e. If you change the attribute in the backend via python it should update in the frontend. And if you change the attribute in the frontend via JS you should be able to subscribe and react to that event in the python backend. This is not supported (i believe) for the css_classes attribute and that is a bit problematic as webframeworks like bootstrap and online examples uses the possibility to add/ remove css classes to change the layout and styling interactively. It just makes it harder to do that kind of thing via Python alone.

**Comment by mattpap** [comment]
From bokeh's perspective, the generated HTML (well, DOM to be specific, but I will use those terms interchangeably) and related CSS are private implementation details, and as such shouldn't be queried or modified outside of views. Bokeh treats HTML/CSS as a backend, and is not, in its current form, an abstraction layer on top of those. That's why bokeh doesn't provide a way to identify HTML elements and doesn't encourage to touch its CSS. There is `css_classes` property on DOM layoutable components, which is an unfortunate artifact, and is used primarily for testing/debugging in bokeh. Having HTML/CSS private means those can change at any time, including minor bokeh versions, so anything that relies on those, is likely to work only for a specific version of bokeh. To reiterate, we don't guarantee backwards compatibility for HTML/CSS.

What you propose in this issue, is technically possible, including updating models based on DOM changes. This can be done efficiently and in a cross browser compatible way. This just doesn't match what bokeh was designed for. I think that the optimal solution, though also the most expensive one, is to allow both managed (the existing design) and unmanaged components in bokeh. This is a conclusion I already came to after recent layout issues and discussion.

**Comment by philippjfr** [comment]
>There is css_classes property on DOM layoutable components, which is an unfortunate artifact, and is used primarily for testing/debugging in bokeh.

This does not seem to have ever been documented, indeed the PR introducing that property (https://github.com/bokeh/bokeh/pull/5503) explicitly does not mention that purpose and one of @bryevdv's SO comments states:

>This PR "Add support for specifying CSS classes on all LayoutDOM" will be going into Bokeh 0.12.4 in Dec 2017 and provided a mechanism to add arbitrary CSS classes to any Bokeh LayoutDOM model (e.g. widgets) so that they can be more easily styled.

A [quick search](https://www.google.com/search?q=bokeh+css_classes+site:stackoverflow.com) also shows how frequently this feature has been employed. It would be good to clarify this.

**Comment by mattpap** [comment]
My comment was based on usage of `css_classes` in bokeh, where it appears in one (!) example, which just shows off this particular feature. There is no documentation besides a docstring. However, it appears in integration tests, where it's used for HTML element identification.

As with some other bokeh's features, the true motivation for adding `css_classes` was to provide a "relief mechanism", i.e. the user can do whatever he wants, but there are few or no guarantees given. This was added at the time, when some of bokeh devs though that exposing every implementation detail was a good idea.

`css_classes` and any attempts to modify HTML/CSS of bokeh's components would make sense if bokeh was more closely aligned with or was just a thin abstraction layer on top of those.

**Comment by bryevdv** [comment]
The feature is documented (it is in the reference guide), but not well demonstrated. 

We are never going to be able to provide a knob to control everything users might (very reasonably) want to style. There is no managed/unmanaged. There is only some arbitrary degree of partial management (and possibly different levels of such).  In any I view things like `css_classes` as a necessity to cater to and retain a very wide range of users with different expectations and abilities. If we don't want to lose users who are frustrated because they can't do something as simple as make colors match their mandated company theme, we must be pragmatic.

**Comment by philippjfr** [comment]
Thanks for clarifying both of you. If you consider this request at all reasonable it should be moved to bokeh since it's not something we can control at the Panel level.

**Comment by bryevdv** [comment]
I think it's reasonable to consider. Which I guess I should be expressly clear about what that means to me:

* It could be useful to help simplify integration tests slightly
* It could be useful to some subset of knowledgeable users, BUT:
* It's not necessarily something I would promote or actively encourage

The question to answer is whether anything currently sets id values on DOM components  that correspond to Bokeh models or not. E.g. we definitely currently set ids on divs that content gets embedded *into*, but a `css_id` on models would not conflict with those. Do any models themselves set ids that a `css_id` might conflict directly with?

**Comment by mattpap** [comment]
> The feature is documented (it is in the reference guide), but not well demonstrated.

There's nothing under `sphinx/` except for a release note. `docstring` was already mentioned, but it doesn't explain much.

> We are never going to be able to provide a knob to control everything users might (very reasonably) want to style. (...) If we don't want to lose users who are frustrated because they can't do something as simple as make widget colors match their mandated company theme, we must be pragmatic.

We can provide such control and it's called CSS. The problem is that bokeh doesn't play well with it (layout was already mentioned, but there are other reasons; see at the end). Which actually is a feature in my option, assuming that bokeh would provide any decent level of customizability outside of plots. In particular widgets are a huge offender, because they haven't received the attention they deserve. Obviously I would like bokeh to respect CSS, but it would have been even better if applying a basic logotype, wouldn't require fiddling with devtools. One of the big advantages of having CSS "managed" for you, is cross-browser compatibility. As soon as one touches any of it, you are on your own. This problem was reduced in significance over the years, so it may not be that apparent anymore.

Let's say I would like to have a consistent face color of all kinds of buttons and button-like controls in a bokeh dashboard. This includes tool buttons, date picker's buttons, slider handles, data table column headers, etc. How do I approach this and how do I make this forwards compatible? Either I find all related CSS classes (possibly third-party) or add my own CSS classes to bokeh's elements, but then I still will need to figure out sub-selectors (especially in third-party cases). A simple bokeh `Button` widget consists of three `div`s. Which one do I style? Does the DOM structure depend on model properties? Is it going to change in the next minor version? That's a lot of internal knowledge to have. So, let's call that a pragmatic approach. After all the user can do anything, just I'm not sure if he's going to stay with bokeh for long.

> Do any models themselves set ids that a `css_id` might conflict directly with?

Models don't set any IDs. If anything, views could, but they don't. They used to at some point, but I removed that (it was an auto-generated ID anyway). It should be possible to create multiple views per model, but currently this doesn't work (`PlotView` is a good offender), so a model-set ID may not identify a single HTML element uniquely. Then there's a possibility for a model to have a view that may or may not have an HTML element rendered for. It's already a possibility with `render_mode` (e.g. annotations) and is even more prominent in my current work on grid and sub plots. This makes `css_classes` inapplicable as well.

**Comment by bryevdv** [comment]
> A simple bokeh Button widget consists of three divs. Which one do I style? Does the DOM structure depend on model properties? Is it going to change in the next minor version? That's a lot of internal knowledge to have. So, let's call that a pragmatic approach. After all the user can do anything, just I'm not sure if he's going to stay with bokeh for long.

Front end devs have to put up with all of this mess already, just as a matter of course. Let's clarify: these features are for specifically for Bokeh users who also are willing to do some front-end dev (And know how to do it) to get exactly the results they want. As long as affording them that capability does not actively interfere with all the users who *don't* want to ever do any front-end-ish work at all, I can see no negatives *at all* to offering it. Should we work to provide more stability and guarantees over time to the extent we call? Absolutely.

The fact that CSS controls both layout and styling is obviously the tension here but there's nothing we can do about that. We are always going to manage both to some extent, but in the limit, the set of all users will want infinite control over stying so we must provide avenues to get there even if they are not perfectly ideal.

**Comment by philippjfr** [comment]
Appreciate all the discussion here, given the work to expose stylesheets from Python in Bokeh 3.0 I don't think this is needed anymore. Indeed once elements are in the shadow DOM the `id` won't be all that useful. I'd say if this is still going to be useful it should be raised at the bokeh level, so I'll close here.
